language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email:
    recipients:
      - soloamimepasa91@gmail.com
    on_success: always
    on_failure: always
before_install:
  - chmod +x mvnw
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test